### ISSUE TITLE
build

### ISSUE THREAD

**Issue by noisecode3** [drobilla/raul#1]
Hey I get this from you build script on Manjaro
`./waf configure
Traceback (most recent call last):
  File "./waf", line 5, in <module>
    from waflib import Context, Scripting
ImportError: cannot import name 'Context' from 'waflib' (unknown location)
`

**Comment by drobilla** [comment]
You need to update submodules.

https://github.com/drobilla/raul/commit/14d9ddc7441f401117bdf27663a5ddf9237425d2
